<?php

class Countries
{
    public function getCountries(): array
    {
        return [
            ["name" => "Afghanistan", "code" => "AF", "phone" => "93", "currency" => "AFN", "symbol" => "؋"],
            ["name" => "Aland Islands", "code" => "AX", "phone" => "358", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Albania", "code" => "AL", "phone" => "355", "currency" => "ALL", "symbol" => "Lek"],
            ["name" => "Algeria", "code" => "DZ", "phone" => "213", "currency" => "DZD", "symbol" => "دج"],
            ["name" => "American Samoa", "code" => "AS", "phone" => "1684", "currency" => "USD", "symbol" => "$"],
            ["name" => "Andorra", "code" => "AD", "phone" => "376", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Angola", "code" => "AO", "phone" => "244", "currency" => "AOA", "symbol" => "Kz"],
            ["name" => "Anguilla", "code" => "AI", "phone" => "1264", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Antarctica", "code" => "AQ", "phone" => "672", "currency" => "AAD", "symbol" => "$"],
            ["name" => "Antigua and Barbuda", "code" => "AG", "phone" => "1268", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Argentina", "code" => "AR", "phone" => "54", "currency" => "ARS", "symbol" => "$"],
            ["name" => "Armenia", "code" => "AM", "phone" => "374", "currency" => "AMD", "symbol" => "֏"],
            ["name" => "Aruba", "code" => "AW", "phone" => "297", "currency" => "AWG", "symbol" => "ƒ"],
            ["name" => "Australia", "code" => "AU", "phone" => "61", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Austria", "code" => "AT", "phone" => "43", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Azerbaijan", "code" => "AZ", "phone" => "994", "currency" => "AZN", "symbol" => "m"],
            ["name" => "Bahamas", "code" => "BS", "phone" => "1242", "currency" => "BSD", "symbol" => "B$"],
            ["name" => "Bahrain", "code" => "BH", "phone" => "973", "currency" => "BHD", "symbol" => ".د.ب"],
            ["name" => "Bangladesh", "code" => "BD", "phone" => "880", "currency" => "BDT", "symbol" => "৳"],
            ["name" => "Barbados", "code" => "BB", "phone" => "1246", "currency" => "BBD", "symbol" => "Bds$"],
            ["name" => "Belarus", "code" => "BY", "phone" => "375", "currency" => "BYN", "symbol" => "Br"],
            ["name" => "Belgium", "code" => "BE", "phone" => "32", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Belize", "code" => "BZ", "phone" => "501", "currency" => "BZD", "symbol" => "$"],
            ["name" => "Benin", "code" => "BJ", "phone" => "229", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Bermuda", "code" => "BM", "phone" => "1441", "currency" => "BMD", "symbol" => "$"],
            ["name" => "Bhutan", "code" => "BT", "phone" => "975", "currency" => "BTN", "symbol" => "Nu."],
            ["name" => "Bolivia", "code" => "BO", "phone" => "591", "currency" => "BOB", "symbol" => "Bs."],
            ["name" => "Bonaire, Sint Eustatius and Saba", "code" => "BQ", "phone" => "599", "currency" => "USD", "symbol" => "$"],
            ["name" => "Bosnia and Herzegovina", "code" => "BA", "phone" => "387", "currency" => "BAM", "symbol" => "KM"],
            ["name" => "Botswana", "code" => "BW", "phone" => "267", "currency" => "BWP", "symbol" => "P"],
            ["name" => "Bouvet Island", "code" => "BV", "phone" => "55", "currency" => "NOK", "symbol" => "kr"],
            ["name" => "Brazil", "code" => "BR", "phone" => "55", "currency" => "BRL", "symbol" => "R$"],
            ["name" => "British Indian Ocean Territory", "code" => "IO", "phone" => "246", "currency" => "USD", "symbol" => "$"],
            ["name" => "Brunei Darussalam", "code" => "BN", "phone" => "673", "currency" => "BND", "symbol" => "B$"],
            ["name" => "Bulgaria", "code" => "BG", "phone" => "359", "currency" => "BGN", "symbol" => "Лв."],
            ["name" => "Burkina Faso", "code" => "BF", "phone" => "226", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Burundi", "code" => "BI", "phone" => "257", "currency" => "BIF", "symbol" => "FBu"],
            ["name" => "Cambodia", "code" => "KH", "phone" => "855", "currency" => "KHR", "symbol" => "KHR"],
            ["name" => "Cameroon", "code" => "CM", "phone" => "237", "currency" => "XAF", "symbol" => "FCFA"],
            ["name" => "Canada", "code" => "CA", "phone" => "1", "currency" => "CAD", "symbol" => "$"],
            ["name" => "Cape Verde", "code" => "CV", "phone" => "238", "currency" => "CVE", "symbol" => "$"],
            ["name" => "Cayman Islands", "code" => "KY", "phone" => "1345", "currency" => "KYD", "symbol" => "$"],
            ["name" => "Central African Republic", "code" => "CF", "phone" => "236", "currency" => "XAF", "symbol" => "FCFA"],
            ["name" => "Chad", "code" => "TD", "phone" => "235", "currency" => "XAF", "symbol" => "FCFA"],
            ["name" => "Chile", "code" => "CL", "phone" => "56", "currency" => "CLP", "symbol" => "$"],
            ["name" => "China", "code" => "CN", "phone" => "86", "currency" => "CNY", "symbol" => "¥"],
            ["name" => "Christmas Island", "code" => "CX", "phone" => "61", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Cocos (Keeling) Islands", "code" => "CC", "phone" => "672", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Colombia", "code" => "CO", "phone" => "57", "currency" => "COP", "symbol" => "$"],
            ["name" => "Comoros", "code" => "KM", "phone" => "269", "currency" => "KMF", "symbol" => "CF"],
            ["name" => "Congo", "code" => "CG", "phone" => "242", "currency" => "XAF", "symbol" => "FC"],
            ["name" => "Congo, Democratic Republic of the Congo", "code" => "CD", "phone" => "242", "currency" => "CDF", "symbol" => "FC"],
            ["name" => "Cook Islands", "code" => "CK", "phone" => "682", "currency" => "NZD", "symbol" => "$"],
            ["name" => "Costa Rica", "code" => "CR", "phone" => "506", "currency" => "CRC", "symbol" => "₡"],
            ["name" => "Cote D'Ivoire", "code" => "CI", "phone" => "225", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Croatia", "code" => "HR", "phone" => "385", "currency" => "HRK", "symbol" => "kn"],
            ["name" => "Cuba", "code" => "CU", "phone" => "53", "currency" => "CUP", "symbol" => "$"],
            ["name" => "Curacao", "code" => "CW", "phone" => "599", "currency" => "ANG", "symbol" => "ƒ"],
            ["name" => "Cyprus", "code" => "CY", "phone" => "357", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Czech Republic", "code" => "CZ", "phone" => "420", "currency" => "CZK", "symbol" => "Kč"],
            ["name" => "Denmark", "code" => "DK", "phone" => "45", "currency" => "DKK", "symbol" => "Kr."],
            ["name" => "Djibouti", "code" => "DJ", "phone" => "253", "currency" => "DJF", "symbol" => "Fdj"],
            ["name" => "Dominica", "code" => "DM", "phone" => "1767", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Dominican Republic", "code" => "DO", "phone" => "1809", "currency" => "DOP", "symbol" => "$"],
            ["name" => "Ecuador", "code" => "EC", "phone" => "593", "currency" => "USD", "symbol" => "$"],
            ["name" => "Egypt", "code" => "EG", "phone" => "20", "currency" => "EGP", "symbol" => "ج.م"],
            ["name" => "El Salvador", "code" => "SV", "phone" => "503", "currency" => "USD", "symbol" => "$"],
            ["name" => "Equatorial Guinea", "code" => "GQ", "phone" => "240", "currency" => "XAF", "symbol" => "FCFA"],
            ["name" => "Eritrea", "code" => "ER", "phone" => "291", "currency" => "ERN", "symbol" => "Nfk"],
            ["name" => "Estonia", "code" => "EE", "phone" => "372", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Ethiopia", "code" => "ET", "phone" => "251", "currency" => "ETB", "symbol" => "Nkf"],
            ["name" => "Falkland Islands (Malvinas)", "code" => "FK", "phone" => "500", "currency" => "FKP", "symbol" => "£"],
            ["name" => "Faroe Islands", "code" => "FO", "phone" => "298", "currency" => "DKK", "symbol" => "Kr."],
            ["name" => "Fiji", "code" => "FJ", "phone" => "679", "currency" => "FJD", "symbol" => "FJ$"],
            ["name" => "Finland", "code" => "FI", "phone" => "358", "currency" => "EUR", "symbol" => "€"],
            ["name" => "France", "code" => "FR", "phone" => "33", "currency" => "EUR", "symbol" => "€"],
            ["name" => "French Guiana", "code" => "GF", "phone" => "594", "currency" => "EUR", "symbol" => "€"],
            ["name" => "French Polynesia", "code" => "PF", "phone" => "689", "currency" => "XPF", "symbol" => "₣"],
            ["name" => "French Southern Territories", "code" => "TF", "phone" => "262", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Gabon", "code" => "GA", "phone" => "241", "currency" => "XAF", "symbol" => "FCFA"],
            ["name" => "Gambia", "code" => "GM", "phone" => "220", "currency" => "GMD", "symbol" => "D"],
            ["name" => "Georgia", "code" => "GE", "phone" => "995", "currency" => "GEL", "symbol" => "ლ"],
            ["name" => "Germany", "code" => "DE", "phone" => "49", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Ghana", "code" => "GH", "phone" => "233", "currency" => "GHS", "symbol" => "GH₵"],
            ["name" => "Gibraltar", "code" => "GI", "phone" => "350", "currency" => "GIP", "symbol" => "£"],
            ["name" => "Greece", "code" => "GR", "phone" => "30", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Greenland", "code" => "GL", "phone" => "299", "currency" => "DKK", "symbol" => "Kr."],
            ["name" => "Grenada", "code" => "GD", "phone" => "1473", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Guadeloupe", "code" => "GP", "phone" => "590", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Guam", "code" => "GU", "phone" => "1671", "currency" => "USD", "symbol" => "$"],
            ["name" => "Guatemala", "code" => "GT", "phone" => "502", "currency" => "GTQ", "symbol" => "Q"],
            ["name" => "Guernsey", "code" => "GG", "phone" => "44", "currency" => "GBP", "symbol" => "£"],
            ["name" => "Guinea", "code" => "GN", "phone" => "224", "currency" => "GNF", "symbol" => "FG"],
            ["name" => "Guinea-Bissau", "code" => "GW", "phone" => "245", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Guyana", "code" => "GY", "phone" => "592", "currency" => "GYD", "symbol" => "$"],
            ["name" => "Haiti", "code" => "HT", "phone" => "509", "currency" => "HTG", "symbol" => "G"],
            ["name" => "Heard Island and Mcdonald Islands", "code" => "HM", "phone" => "0", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Holy See (Vatican City State)", "code" => "VA", "phone" => "39", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Honduras", "code" => "HN", "phone" => "504", "currency" => "HNL", "symbol" => "L"],
            ["name" => "Hong Kong", "code" => "HK", "phone" => "852", "currency" => "HKD", "symbol" => "$"],
            ["name" => "Hungary", "code" => "HU", "phone" => "36", "currency" => "HUF", "symbol" => "Ft"],
            ["name" => "Iceland", "code" => "IS", "phone" => "354", "currency" => "ISK", "symbol" => "kr"],
            ["name" => "India", "code" => "IN", "phone" => "91", "currency" => "INR", "symbol" => "₹"],
            ["name" => "Indonesia", "code" => "ID", "phone" => "62", "currency" => "IDR", "symbol" => "Rp"],
            ["name" => "Iran, Islamic Republic of", "code" => "IR", "phone" => "98", "currency" => "IRR", "symbol" => "﷼"],
            ["name" => "Iraq", "code" => "IQ", "phone" => "964", "currency" => "IQD", "symbol" => "د.ع"],
            ["name" => "Ireland", "code" => "IE", "phone" => "353", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Isle of Man", "code" => "IM", "phone" => "44", "currency" => "GBP", "symbol" => "£"],
            ["name" => "Israel", "code" => "IL", "phone" => "972", "currency" => "ILS", "symbol" => "₪"],
            ["name" => "Italy", "code" => "IT", "phone" => "39", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Jamaica", "code" => "JM", "phone" => "1876", "currency" => "JMD", "symbol" => "J$"],
            ["name" => "Japan", "code" => "JP", "phone" => "81", "currency" => "JPY", "symbol" => "¥"],
            ["name" => "Jersey", "code" => "JE", "phone" => "44", "currency" => "GBP", "symbol" => "£"],
            ["name" => "Jordan", "code" => "JO", "phone" => "962", "currency" => "JOD", "symbol" => "ا.د"],
            ["name" => "Kazakhstan", "code" => "KZ", "phone" => "7", "currency" => "KZT", "symbol" => "лв"],
            ["name" => "Kenya", "code" => "KE", "phone" => "254", "currency" => "KES", "symbol" => "KSh"],
            ["name" => "Kiribati", "code" => "KI", "phone" => "686", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Korea, Democratic People's Republic of", "code" => "KP", "phone" => "850", "currency" => "KPW", "symbol" => "₩"],
            ["name" => "Korea, Republic of", "code" => "KR", "phone" => "82", "currency" => "KRW", "symbol" => "₩"],
            ["name" => "Kosovo", "code" => "XK", "phone" => "381", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Kuwait", "code" => "KW", "phone" => "965", "currency" => "KWD", "symbol" => "ك.د"],
            ["name" => "Kyrgyzstan", "code" => "KG", "phone" => "996", "currency" => "KGS", "symbol" => "лв"],
            ["name" => "Lao People's Democratic Republic", "code" => "LA", "phone" => "856", "currency" => "LAK", "symbol" => "₭"],
            ["name" => "Latvia", "code" => "LV", "phone" => "371", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Lebanon", "code" => "LB", "phone" => "961", "currency" => "LBP", "symbol" => "£"],
            ["name" => "Lesotho", "code" => "LS", "phone" => "266", "currency" => "LSL", "symbol" => "L"],
            ["name" => "Liberia", "code" => "LR", "phone" => "231", "currency" => "LRD", "symbol" => "$"],
            ["name" => "Libyan Arab Jamahiriya", "code" => "LY", "phone" => "218", "currency" => "LYD", "symbol" => "د.ل"],
            ["name" => "Liechtenstein", "code" => "LI", "phone" => "423", "currency" => "CHF", "symbol" => "CHf"],
            ["name" => "Lithuania", "code" => "LT", "phone" => "370", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Luxembourg", "code" => "LU", "phone" => "352", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Macao", "code" => "MO", "phone" => "853", "currency" => "MOP", "symbol" => "$"],
            ["name" => "Macedonia, the Former Yugoslav Republic of", "code" => "MK", "phone" => "389", "currency" => "MKD", "symbol" => "ден"],
            ["name" => "Madagascar", "code" => "MG", "phone" => "261", "currency" => "MGA", "symbol" => "Ar"],
            ["name" => "Malawi", "code" => "MW", "phone" => "265", "currency" => "MWK", "symbol" => "MK"],
            ["name" => "Malaysia", "code" => "MY", "phone" => "60", "currency" => "MYR", "symbol" => "RM"],
            ["name" => "Maldives", "code" => "MV", "phone" => "960", "currency" => "MVR", "symbol" => "Rf"],
            ["name" => "Mali", "code" => "ML", "phone" => "223", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Malta", "code" => "MT", "phone" => "356", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Marshall Islands", "code" => "MH", "phone" => "692", "currency" => "USD", "symbol" => "$"],
            ["name" => "Martinique", "code" => "MQ", "phone" => "596", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Mauritania", "code" => "MR", "phone" => "222", "currency" => "MRO", "symbol" => "MRU"],
            ["name" => "Mauritius", "code" => "MU", "phone" => "230", "currency" => "MUR", "symbol" => "₨"],
            ["name" => "Mayotte", "code" => "YT", "phone" => "269", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Mexico", "code" => "MX", "phone" => "52", "currency" => "MXN", "symbol" => "$"],
            ["name" => "Micronesia, Federated States of", "code" => "FM", "phone" => "691", "currency" => "USD", "symbol" => "$"],
            ["name" => "Moldova, Republic of", "code" => "MD", "phone" => "373", "currency" => "MDL", "symbol" => "L"],
            ["name" => "Monaco", "code" => "MC", "phone" => "377", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Mongolia", "code" => "MN", "phone" => "976", "currency" => "MNT", "symbol" => "₮"],
            ["name" => "Montenegro", "code" => "ME", "phone" => "382", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Montserrat", "code" => "MS", "phone" => "1664", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Morocco", "code" => "MA", "phone" => "212", "currency" => "MAD", "symbol" => "DH"],
            ["name" => "Mozambique", "code" => "MZ", "phone" => "258", "currency" => "MZN", "symbol" => "MT"],
            ["name" => "Myanmar", "code" => "MM", "phone" => "95", "currency" => "MMK", "symbol" => "K"],
            ["name" => "Namibia", "code" => "NA", "phone" => "264", "currency" => "NAD", "symbol" => "$"],
            ["name" => "Nauru", "code" => "NR", "phone" => "674", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Nepal", "code" => "NP", "phone" => "977", "currency" => "NPR", "symbol" => "₨"],
            ["name" => "Netherlands", "code" => "NL", "phone" => "31", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Netherlands Antilles", "code" => "AN", "phone" => "599", "currency" => "ANG", "symbol" => "NAf"],
            ["name" => "New Caledonia", "code" => "NC", "phone" => "687", "currency" => "XPF", "symbol" => "₣"],
            ["name" => "New Zealand", "code" => "NZ", "phone" => "64", "currency" => "NZD", "symbol" => "$"],
            ["name" => "Nicaragua", "code" => "NI", "phone" => "505", "currency" => "NIO", "symbol" => "C$"],
            ["name" => "Niger", "code" => "NE", "phone" => "227", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Nigeria", "code" => "NG", "phone" => "234", "currency" => "NGN", "symbol" => "₦"],
            ["name" => "Niue", "code" => "NU", "phone" => "683", "currency" => "NZD", "symbol" => "$"],
            ["name" => "Norfolk Island", "code" => "NF", "phone" => "672", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Northern Mariana Islands", "code" => "MP", "phone" => "1670", "currency" => "USD", "symbol" => "$"],
            ["name" => "Norway", "code" => "NO", "phone" => "47", "currency" => "NOK", "symbol" => "kr"],
            ["name" => "Oman", "code" => "OM", "phone" => "968", "currency" => "OMR", "symbol" => ".ع.ر"],
            ["name" => "Pakistan", "code" => "PK", "phone" => "92", "currency" => "PKR", "symbol" => "₨"],
            ["name" => "Palau", "code" => "PW", "phone" => "680", "currency" => "USD", "symbol" => "$"],
            ["name" => "Palestinian Territory, Occupied", "code" => "PS", "phone" => "970", "currency" => "ILS", "symbol" => "₪"],
            ["name" => "Panama", "code" => "PA", "phone" => "507", "currency" => "PAB", "symbol" => "B/."],
            ["name" => "Papua New Guinea", "code" => "PG", "phone" => "675", "currency" => "PGK", "symbol" => "K"],
            ["name" => "Paraguay", "code" => "PY", "phone" => "595", "currency" => "PYG", "symbol" => "₲"],
            ["name" => "Peru", "code" => "PE", "phone" => "51", "currency" => "PEN", "symbol" => "S/."],
            ["name" => "Philippines", "code" => "PH", "phone" => "63", "currency" => "PHP", "symbol" => "₱"],
            ["name" => "Pitcairn", "code" => "PN", "phone" => "64", "currency" => "NZD", "symbol" => "$"],
            ["name" => "Poland", "code" => "PL", "phone" => "48", "currency" => "PLN", "symbol" => "zł"],
            ["name" => "Portugal", "code" => "PT", "phone" => "351", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Puerto Rico", "code" => "PR", "phone" => "1787", "currency" => "USD", "symbol" => "$"],
            ["name" => "Qatar", "code" => "QA", "phone" => "974", "currency" => "QAR", "symbol" => "ق.ر"],
            ["name" => "Reunion", "code" => "RE", "phone" => "262", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Romania", "code" => "RO", "phone" => "40", "currency" => "RON", "symbol" => "lei"],
            ["name" => "Russian Federation", "code" => "RU", "phone" => "70", "currency" => "RUB", "symbol" => "₽"],
            ["name" => "Rwanda", "code" => "RW", "phone" => "250", "currency" => "RWF", "symbol" => "FRw"],
            ["name" => "Saint Barthelemy", "code" => "BL", "phone" => "590", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Saint Helena", "code" => "SH", "phone" => "290", "currency" => "SHP", "symbol" => "£"],
            ["name" => "Saint Kitts and Nevis", "code" => "KN", "phone" => "1869", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Saint Lucia", "code" => "LC", "phone" => "1758", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Saint Martin", "code" => "MF", "phone" => "590", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Saint Pierre and Miquelon", "code" => "PM", "phone" => "508", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Saint Vincent and the Grenadines", "code" => "VC", "phone" => "1784", "currency" => "XCD", "symbol" => "$"],
            ["name" => "Samoa", "code" => "WS", "phone" => "684", "currency" => "WST", "symbol" => "SAT"],
            ["name" => "San Marino", "code" => "SM", "phone" => "378", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Sao Tome and Principe", "code" => "ST", "phone" => "239", "currency" => "STD", "symbol" => "Db"],
            ["name" => "Saudi Arabia", "code" => "SA", "phone" => "966", "currency" => "SAR", "symbol" => "﷼"],
            ["name" => "Senegal", "code" => "SN", "phone" => "221", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Serbia", "code" => "RS", "phone" => "381", "currency" => "RSD", "symbol" => "din"],
            ["name" => "Serbia and Montenegro", "code" => "CS", "phone" => "381", "currency" => "RSD", "symbol" => "din"],
            ["name" => "Seychelles", "code" => "SC", "phone" => "248", "currency" => "SCR", "symbol" => "SRe"],
            ["name" => "Sierra Leone", "code" => "SL", "phone" => "232", "currency" => "SLL", "symbol" => "Le"],
            ["name" => "Singapore", "code" => "SG", "phone" => "65", "currency" => "SGD", "symbol" => "$"],
            ["name" => "Sint Maarten", "code" => "SX", "phone" => "1", "currency" => "ANG", "symbol" => "ƒ"],
            ["name" => "Slovakia", "code" => "SK", "phone" => "421", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Slovenia", "code" => "SI", "phone" => "386", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Solomon Islands", "code" => "SB", "phone" => "677", "currency" => "SBD", "symbol" => "Si$"],
            ["name" => "Somalia", "code" => "SO", "phone" => "252", "currency" => "SOS", "symbol" => "Sh.so."],
            ["name" => "South Africa", "code" => "ZA", "phone" => "27", "currency" => "ZAR", "symbol" => "R"],
            ["name" => "South Georgia and the South Sandwich Islands", "code" => "GS", "phone" => "500", "currency" => "GBP", "symbol" => "£"],
            ["name" => "South Sudan", "code" => "SS", "phone" => "211", "currency" => "SSP", "symbol" => "£"],
            ["name" => "Spain", "code" => "ES", "phone" => "34", "currency" => "EUR", "symbol" => "€"],
            ["name" => "Sri Lanka", "code" => "LK", "phone" => "94", "currency" => "LKR", "symbol" => "Rs"],
            ["name" => "Sudan", "code" => "SD", "phone" => "249", "currency" => "SDG", "symbol" => ".س.ج"],
            ["name" => "Suriname", "code" => "SR", "phone" => "597", "currency" => "SRD", "symbol" => "$"],
            ["name" => "Svalbard and Jan Mayen", "code" => "SJ", "phone" => "47", "currency" => "NOK", "symbol" => "kr"],
            ["name" => "Swaziland", "code" => "SZ", "phone" => "268", "currency" => "SZL", "symbol" => "E"],
            ["name" => "Sweden", "code" => "SE", "phone" => "46", "currency" => "SEK", "symbol" => "kr"],
            ["name" => "Switzerland", "code" => "CH", "phone" => "41", "currency" => "CHF", "symbol" => "CHf"],
            ["name" => "Syrian Arab Republic", "code" => "SY", "phone" => "963", "currency" => "SYP", "symbol" => "LS"],
            ["name" => "Taiwan, Province of China", "code" => "TW", "phone" => "886", "currency" => "TWD", "symbol" => "$"],
            ["name" => "Tajikistan", "code" => "TJ", "phone" => "992", "currency" => "TJS", "symbol" => "SM"],
            ["name" => "Tanzania, United Republic of", "code" => "TZ", "phone" => "255", "currency" => "TZS", "symbol" => "TSh"],
            ["name" => "Thailand", "code" => "TH", "phone" => "66", "currency" => "THB", "symbol" => "฿"],
            ["name" => "Timor-Leste", "code" => "TL", "phone" => "670", "currency" => "USD", "symbol" => "$"],
            ["name" => "Togo", "code" => "TG", "phone" => "228", "currency" => "XOF", "symbol" => "CFA"],
            ["name" => "Tokelau", "code" => "TK", "phone" => "690", "currency" => "NZD", "symbol" => "$"],
            ["name" => "Tonga", "code" => "TO", "phone" => "676", "currency" => "TOP", "symbol" => "$"],
            ["name" => "Trinidad and Tobago", "code" => "TT", "phone" => "1868", "currency" => "TTD", "symbol" => "$"],
            ["name" => "Tunisia", "code" => "TN", "phone" => "216", "currency" => "TND", "symbol" => "ت.د"],
            ["name" => "Turkey", "code" => "TR", "phone" => "90", "currency" => "TRY", "symbol" => "₺"],
            ["name" => "Turkmenistan", "code" => "TM", "phone" => "7370", "currency" => "TMT", "symbol" => "T"],
            ["name" => "Turks and Caicos Islands", "code" => "TC", "phone" => "1649", "currency" => "USD", "symbol" => "$"],
            ["name" => "Tuvalu", "code" => "TV", "phone" => "688", "currency" => "AUD", "symbol" => "$"],
            ["name" => "Uganda", "code" => "UG", "phone" => "256", "currency" => "UGX", "symbol" => "USh"],
            ["name" => "Ukraine", "code" => "UA", "phone" => "380", "currency" => "UAH", "symbol" => "₴"],
            ["name" => "United Arab Emirates", "code" => "AE", "phone" => "971", "currency" => "AED", "symbol" => "إ.د"],
            ["name" => "United Kingdom", "code" => "GB", "phone" => "44", "currency" => "GBP", "symbol" => "£"],
            ["name" => "United States", "code" => "US", "phone" => "1", "currency" => "USD", "symbol" => "$"],
            ["name" => "United States Minor Outlying Islands", "code" => "UM", "phone" => "1", "currency" => "USD", "symbol" => "$"],
            ["name" => "Uruguay", "code" => "UY", "phone" => "598", "currency" => "UYU", "symbol" => "$"],
            ["name" => "Uzbekistan", "code" => "UZ", "phone" => "998", "currency" => "UZS", "symbol" => "лв"],
            ["name" => "Vanuatu", "code" => "VU", "phone" => "678", "currency" => "VUV", "symbol" => "VT"],
            ["name" => "Venezuela", "code" => "VE", "phone" => "58", "currency" => "VEF", "symbol" => "Bs"],
            ["name" => "Viet Nam", "code" => "VN", "phone" => "84", "currency" => "VND", "symbol" => "₫"],
            ["name" => "Virgin Islands, British", "code" => "VG", "phone" => "1284", "currency" => "USD", "symbol" => "$"],
            ["name" => "Virgin Islands, U.s.", "code" => "VI", "phone" => "1340", "currency" => "USD", "symbol" => "$"],
            ["name" => "Wallis and Futuna", "code" => "WF", "phone" => "681", "currency" => "XPF", "symbol" => "₣"],
            ["name" => "Western Sahara", "code" => "EH", "phone" => "212", "currency" => "MAD", "symbol" => "MAD"],
            ["name" => "Yemen", "code" => "YE", "phone" => "967", "currency" => "YER", "symbol" => "﷼"],
            ["name" => "Zambia", "code" => "ZM", "phone" => "260", "currency" => "ZMW", "symbol" => "ZK"],
            ["name" => "Zimbabwe", "code" => "ZW", "phone" => "263", "currency" => "ZWL", "symbol" => "$"],
        ];
    }
}
